export default {
<<<<<<< HEAD
    ON_LOGIN_SUCCESS :"ON_LOGIN-SUCCESS",
    ON_LOGIN_FAIL : "ON_LOGIN_FAIL",
    ON_LOGOUT_SUCCESS: "ON_LOGOUT_SUCCESS"
}
=======
  ON_LOGIN_SUCCESS: "ON_LOGIN_SUCCESS",
  ON_LOGIN_FAIL: "ON_LOGIN_FAIL",
  ON_LOGOUT_SUCCESS: "ON_LOGOUT_SUCCESS",
};
>>>>>>> b3d57fa4d4c7075e9d991868afaa7eaced7bd92e
